### ISSUE TITLE
The problem in the preprocessing step

### ISSUE THREAD

**Issue by Jiuzhouh** [diegma/graph-2-text#11]
Hi, thanks for your contributions.
I met a problem in the preprocessing step. When I run preprocess.py as your instruction, it shows an error. It shows in the pic below: 
<img width="884" alt="error" src="https://user-images.githubusercontent.com/34101235/81045944-a043fd80-8efa-11ea-8166-a29fdd7da790.png">
Could you please help me to find out the error reason? Thank you in advance.

**Comment by ashishu007** [comment]
@JokerJoe99 did you manage to get this one right?
