### ISSUE TITLE
WebNLG generated texts

### ISSUE THREAD

**Issue by abevieiramota** [diegma/graph-2-text#6]
Hi, I'm currently working with the WebNLG data and I'd like to know if the texts generated by the models reported in the paper can be made available.
Thanks in advance.

**Comment by lauhaide** [comment]
Hi, I added a link to the outputs by the GCN_EC model in README.

**Comment by abevieiramota** [comment]
Hi @lauhaide, thanks! It looks like I need some Google Drive permission to access the files, could you check it? 
Also, I'm running some analysis on texts generated for the WebNLG benchmark, and I'd like to know if I can share the GCN_EC texts in my [github repository](https://github.com/abevieiramota/masters), referring to this repository and the paper.

**Comment by lauhaide** [comment]
Hi @abevieiramota, I've updated the links, now you should be able to download!

Sure, you can add links to our repo for the data.

**Comment by abevieiramota** [comment]
I saw that the *_test.txt files contains 2495 lines, but I was expecting 1862, the number of entries in the test set of the 2017 challenge release. Is it in a different format or it was generated using another WebNLG release?

**Comment by abevieiramota** [comment]
Well, looking again, I'm hypothesizing that the files contain texts only for the seen subset of the test set. Also, for each entry, its corresponding text is replicated N times, with N being the number of references texts of the entry. I'll do some checks, but it would be great to have a confirmation from the authors :)

**Comment by lauhaide** [comment]
Hi @abevieiramota, that's correct!

**Comment by abevieiramota** [comment]
Thanks @lauhaide :)
