### ISSUE TITLE
preprocessing script for Dependency parsing data

### ISSUE THREAD

**Issue by atmani-massinissa** [diegma/graph-2-text#8]
Hi,

Thank you for this great paper and also for releasing the code. 
My question is about the preprocessing of other data like dependency parsing, the provided scripts do not handle it I guess. So is it possible to know what is the expected format of the input. Does a Matrix N*N representing the graph structure is enough, or other tricky representations must be added. 

Thanks

**Comment by diegma** [comment]
Thanks for the interest in our work!

The WebNLG and SR11 scripts  
(webnlg_gcnonmt_input.py/sr11_onmtgcn_input.py) read WebNLG and SR11  
data and generate input files encoding the graphs for GCN. The input  
GCN encoder needs the following files:

DATASET-nodes.txt (nodes of the graph, i.e., the words of the sentence)
DATASET-labels.txt (label for an edge, i.e., the label of the syntactic edge)
DATASET-node1.txt (index of arrival node for an edge)
DATASET-node2.txt (index of departure node for an edge)

Note that line N in all files describes the graph data instance N of  
the dataset.

An example:

nodes:  Eastern governingBody GOVERNINGBODY Province , Sri Lanka
labels: A0 A1 NE NE NE NE
node1:   0  2  3  4  5  6
node2:   1  1  0  0  0  0

**Comment by atmani-massinissa** [comment]
OK,

Thank you for your help.
